#!scheme

(if (not (= (length command-line) 3))
    (begin (display "usage: mk-prelude-file <prelude>")
	   (newline)
	   (quit)))

(define (inc i) (+ i 1))

(define (write-string s port)
  (let ((len (string-length s)))
    (let loop ((i 0))
      (if (< i len)
	  (begin (write-char (string-ref s i) port)
		 (loop (inc i)))))))

(define (print-line s port)
  (write-string s port)
  (write-char #\newline port))

(define (skip-char? c previous)
  (or (and (equal? c #\space) (equal? previous #\space))
      (equal? c #\cr)
      (equal? c #\lf)))
	  
(define (dump-prelude in-port out-port)
  (let loop ((c (read-char in-port))
	     (previous-char #\z))	; dummy
    (if (not(eof-object? c))
	(begin (if (not (skip-char? c previous-char))
		   (write-char c out-port))
	       (loop (read-char in-port) c)))))
    
(define in-file-name  (list-ref command-line 2))
(define in-port (open-input-file in-file-name))
(define out-port (open-output-file "prelude.c"))

(print-line "// Auto generated from prelude.scm using mk-prelude-file.scm" out-port)
(print-line "// MIT license" out-port)
(print-line "//" out-port)
(print-line "// Copyright 2025 Per Nilsson" out-port)
(print-line "//" out-port)
(print-line "// Permission is hereby granted, free of charge, to any person obtaining a copy" out-port)
(print-line "// of this software and associated documentation files (the 'Software'), to" out-port)
(print-line "// deal in the Software without restriction, including without limitation the" out-port)
(print-line "// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or" out-port)
(print-line "// sell copies of the Software, and to permit persons to whom the Software is" out-port)
(print-line "// furnished to do so, subject to the following conditions:" out-port)
(print-line "//" out-port)
(print-line "// The above copyright notice and this permission notice shall be included in" out-port)
(print-line "// all copies or substantial portions of the Software." out-port)
(print-line "//" out-port)
(print-line "// THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR" out-port)
(print-line "// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY," out-port)
(print-line "// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE" out-port)
(print-line "// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER" out-port)
(print-line "// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING" out-port)
(print-line "// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER" out-port)
(print-line "// DEALINGS IN THE SOFTWARE." out-port)
(write-string "const char* prelude = R" out-port)
(write-char #\" out-port)
(write-char #\( out-port)
(dump-prelude in-port out-port)
(write-char #\) out-port)
(write-char #\" out-port)
(write-char #\; out-port)

(close-output-port out-port)
(close-input-port in-port)
