#!/usr/local/bin/scheme

(if (not (= (length command-line) 3))
    (begin (display "usage: mk-prelude-file <prelude>")
	   (newline)
	   (quit)))

(define (inc i) (+ i 1))

(define (skip-char? c previous)
  (or (and (equal? c #\space) (equal? previous #\space))
      (equal? c #\cr)
      (equal? c #\lf)))
	  
(define (dump-prelude in-port out-port)
  (let loop ((c (read-char in-port))
	     (previous-char #\z))	; dummy
    (if (not(eof-object? c))
	(begin (if (not (skip-char? c previous-char))
		   (write-char c out-port))
	       (loop (read-char in-port) c)))))
    
(define in-file-name  (list-ref command-line 2))
(define in-port (open-input-file in-file-name))
(define out-port (open-output-file "prelude.c"))

(display "// Auto generated from prelude.scm using mk-prelude-file.scm\n" out-port)
(display "// MIT license\n" out-port)
(display "//\n" out-port)
(display "// Copyright 2025 Per Nilsson\n" out-port)
(display "//\n" out-port)
(display "// Permission is hereby granted, free of charge, to any person obtaining a copy\n" out-port)
(display "// of this software and associated documentation files (the 'Software'), to\n" out-port)
(display "// deal in the Software without restriction, including without limitation the\n" out-port)
(display "// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or\n" out-port)
(display "// sell copies of the Software, and to permit persons to whom the Software is\n" out-port)
(display "// furnished to do so, subject to the following conditions:\n" out-port)
(display "//\n" out-port)
(display "// The above copyright notice and this permission notice shall be included in\n" out-port)
(display "// all copies or substantial portions of the Software.\n" out-port)
(display "//\n" out-port)
(display "// THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n" out-port)
(display "// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n" out-port)
(display "// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n" out-port)
(display "// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n" out-port)
(display "// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING\n" out-port)
(display "// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER\n" out-port)
(display "// DEALINGS IN THE SOFTWARE.\n" out-port)

(display "const char* prelude = R\"(" out-port)
(dump-prelude in-port out-port)
(display ")\";" out-port)

(close-output-port out-port)
(close-input-port in-port)
