(load "/home/per/git/scm/tst/2d-geometry.scm")
(load "/home/per/prg/c++/scheme/keysymdef.scm")
(load "/home/per/git/scm/rgb-colors.scm")

(define window-width 640)
(define window-height 400)
(define ball-diameter 20)
(define pi 3.14159265359)
(define upper-screen-line (<line-2d> (<point-2d> 0 0) (<point-2d> window-width 0)))
(define lower-screen-line (<line-2d> (<point-2d> 0 window-height)
									 (<point-2d> window-width window-height)))
(define left-screen-line (<line-2d> (<point-2d> 0 0) (<point-2d> 0 window-height)))
(define right-screen-line (<line-2d> (<point-2d> window-width 0) (<point-2d> window-width window-height)))

(define (clear-screen)
  (gr-set-foreground white)
  (gr-move-to! 0 0)
  (gr-fill-rect window-width window-height))

(define (calc-move-x angle) (cos angle))
(define (calc-move-y angle) (sin angle))
(define (make-random-ball)
  (make-ball ball-diameter
			 (* (random) window-width)
			 (* (random) window-height)
			 (* (random) (* 2 pi))))

(define (make-ball diameter start-x start-y start-angle)
  (let ((x start-x)
		(y start-y)
		(d diameter)
		(angle start-angle)
		(move-x (calc-move-x start-angle))
		(move-y (calc-move-y start-angle)))
	(define (draw)
	  ;(print-line (list x y))
	  (gr-set-foreground blue)
	  (gr-move-to! x y) 
	  (gr-fill-arc d d 0 (* 360 64)))
	(define (set-angle! phi)
	  (set! angle phi)
	  (set! move-x (calc-move-x start-angle))
	  (set! move-y (calc-move-y start-angle)))
	(define (mirror-up phi)
	  (if (> phi (
	  )
	(define (move)
	  (let ((new-x (+ x move-x))
			(new-y (+ y move-y)))
		(cond ((line-2d-inside-box upper-screen-line x y d d)
		 	   (error "upper-screen-line" angle)
			   (set-angle! (mirror-up angle)))
		 	  ((line-2d-inside-box lower-screen-line x y d d)
			   (error "lower-screen-line" angle))
			  ((line-2d-inside-box left-screen-line x y d d)
			   (error "left-screen-line" angle))
			  ((line-2d-inside-box right-screen-line x y d d)
			   (error "right-screen-line" angle))
			  (else (set! x new-x) (set! y new-y)))))
	(print-line (list x y angle move-x move-y))
	(lambda (message)
	  (match message
		(animate
		 (move)
		 (draw))
		(? (error "BALL: unkown message: " message))))))

(define (run)
  (let  ((running #t)
		 (ball (make-random-ball)))
	(define (handle-events n-events)
      (if (> n-events 0)
		  (let ((event (x-next-event)))
			(match event
			  ((key-press ?win ?x ?y ?state ?key ?str) 
		       (if (= key xk-Q)
				   (begin (print-line event) (set! running #f))
				   (begin (print-line event) (handle-events (dec n-events)))))
			  (? (begin (handle-events (dec n-events))))))))
	(let loop ()
	  (if running
		  (let ((n-events (x-events-queued)))
			(if (= n-events 0)
				(begin (clear-screen)
	  				   (ball 'animate)
					   (gr-swap-buffers)
					   (nano-sleep 0 2000000)
					   (loop))
				(begin (handle-events n-events) (loop))))))))

(gr-open `((width ,window-width)
		   (height ,window-height)
		   (window-name "bouncing ball")))
;(load "/home/per/git/scm/tst/bouncing-ball.scm")
;(run)				   
;(gr-close)
